version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbcontext
    ports: [ "3306:3306"]
    volumes: 
      - .config/mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
    network_mode: bridge

networks:
  mynetwork:
    driver: bridge
    enable_ipv6: true